#version: '3' # Docker Compose 버전 명시

services:
  mysql:
    image: mysql:8.0
    container_name: juseyo-mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpw # MySQL 루트 비밀번호
      MYSQL_DATABASE: juseyodb   # 생성할 기본 데이터베이스 이름
      MYSQL_USER: testuser       # 사용자 이름
      MYSQL_PASSWORD: testpw     # 사용자 비밀번호
    ports:
      - "3307:3306"              # 호스트 포트 3307 -> 컨테이너 포트 3306 매핑
    volumes:
      - mysql-data:/var/lib/mysql # 데이터 지속성을 위한 볼륨 설정
    healthcheck:                  # 헬스체크 추가 (MySQL 상태 확인)
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - juseyo-network

  redis:
    image: redis:latest
    container_name: juseyo-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - juseyo-network

  flask-recommender:
    build:
      context: ./recommendation-app
    container_name: flask-recommender
    ports:
      - "5001:5000"
    restart: unless-stopped
    networks:
      - juseyo-network

  prometheus:
    image: prom/prometheus:latest
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
      - --config.file=/etc/prometheus/prometheus.yml
    container_name: juseyo-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - juseyo-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    container_name: juseyo-grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - juseyo-network
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  k6:
    image: grafana/k6
    container_name: juseyo-k6
    volumes:
      - ./k6:/scripts
    command:
      - run
      - --summary-trend-stats=avg,p95,min,max
      - /scripts/load-test.js
    environment:
      K6_OUT: experimental-prometheus-rw
      K6_PROMETHEUS_RW_SERVER_URL: http://juseyo-prometheus:9090/api/v1/write
      K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM: "true"

    depends_on:
      - prometheus
      - redis
      - mysql
    networks:
      - juseyo-network


  mongodb:
    image: mongo:6.0
    container_name: juseyo-mongo
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: juseyo-chat
    volumes:
      - mongo-data:/data/db
    networks:
      - juseyo-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    networks:
      - juseyo-network




volumes:
  mysql-data:
  redis-data:
  grafana-data:
  mongo-data:

networks:
  juseyo-network:
    driver: bridge