
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpadb
    username: chill
    password: chill
    driver-class-name: com.mysql.cj.jdbc.Driver



jwt:
  access-token-expire-time: 1800000  # 30 * 60 * 1000 = 30분
  refresh-token-expire-time: 10800000 # 3 * 3,600,000  = 3시간
  secretKey: 12345678aldskfjlkj90190123aldfjaslkdfj4567812
  refreshKey: 123456adlkfjasdlkfj789012345678901alsdkjfaslkj23489012
